# Configuration file for Dependabot (https://github.com/dependabot)

version: 2
updates:
  - package-ecosystem: docker
    directory: /
    open-pull-requests-limit: 1
    labels:
      - dependencies
    schedule:
      interval: daily
      time: "05:00"
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 1
    labels:
      - ci
      - dependencies
    schedule:
      interval: daily
      time: "05:00"
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 1
    labels:
      - dependencies
    schedule:
      interval: daily
      time: "05:00"
