# Check out Dependabot at: https://github.com/dependabot

version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 1
    assignees:
      - ericcornelissen
    labels:
      - ci
      - dependencies
    schedule:
      interval: daily
      time: "05:00"
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 1
    assignees:
      - ericcornelissen
    labels:
      - dependencies
    schedule:
      interval: daily
      time: "05:00"
