# Check out ESLint at: https://eslint.org/

plugins:
  - regexp # see https://github.com/ota-meshi/eslint-plugin-regexp

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  regexp/no-super-linear-backtracking:
    - error
    - report: certain
  regexp/no-super-linear-move:
    - error
    - ignorePartial: false
      ignoreSticky: false
      report: certain

overrides:
  - files:
      - "*.ts"
      - "**/*.ts"
    parser: "@typescript-eslint/parser"

ignorePatterns:
  # Cache/temp directories
  - ".cache/**"
  - ".npm/**"
  - ".parcel-cache/**"
  - ".rpt2_cache/**"
  - ".rts2_cache_cjs/**"
  - ".rts2_cache_es/**"
  - ".rts2_cache_umd/**"
  - ".temp/**"
  - ".yarn/cache/**"
  - ".yarn/unplugged/**"

  # Dependency directories
  - "bower_components/**"
  - "jspm_packages/**"
  - "node_modules/**"
  - "vendor/**"
  - "web_modules/**"

  # IDE directories
  - ".idea/**"
  - ".vscode/**"

  # Output directories
  - ".docusaurus/**"
  - ".fusebox/**"
  - ".dynamodb/**"
  - ".grunt/**"
  - ".next/**"
  - ".nuxt/**"
  - ".nyc_output/**"
  - ".serverless/**"
  - ".vuepress/dist/**"
  - "coverage/**"
  - "dist/**"
  - "lib-cov/**"
  - "out/**"
