# Configuration file for Grype (https://github.com/anchore/grype)

output: json
file: vulns.json

fail-on-severity: low

# To identify unused ignore directives, run the two commands below which will
# output the *used* ignore directives. All others are unused and can be pruned.
#     make vulns.json
#     cat vulns.json | jq '[.ignoredMatches[].appliedIgnoreRules]|flatten|unique'
# Based on: <https://github.com/anchore/grype/issues/3050>
ignore:
  - vulnerability: CVE-2025-60876
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-14456
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-14457
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-18798
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-54874
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-63072
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-63073
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-63074
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-63075
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-63076
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-75803
    vex-justification: vulnerable_code_not_in_execute_path

  # Ignore all npm vulnerabilities. This project relies on `npm audit` instead.
  - package:
      type: npm

check-for-app-update: false
