# Check out Grype at: https://github.com/anchore/grype

output: json
file: vulns.json

fail-on-severity: low

ignore:
  # Ignore because this project isn't affected at runtime.
  - vulnerability: CVE-2023-5363

  # Ignore because this project isn't affected at runtime.
  - vulnerability: CVE-2023-5678

  # Ignore because _printf_ isn't used.
  - vulnerability: CVE-2023-42363

  # Ignore because _awk_ isn't used.
  - vulnerability: CVE-2023-42364

  # Ignore because _awk_ isn't used.
  - vulnerability: CVE-2023-42365

  # Ignore because _awk_ isn't used.
  - vulnerability: CVE-2023-42366

  # Ignore all npm vulnerabilities. This project relies on `npm audit` instead.
  - package:
      type: npm
