# Configuration file for Grype (https://github.com/anchore/grype)

output: json
file: vulns.json

fail-on-severity: low

ignore:
  - vulnerability: CVE-2025-60876
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-7383
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-9076
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-34180
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-34181
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-34182
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-34183
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-42764
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-42766
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-42767
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-42768
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-42769
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-42770
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-45445
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-45446
    vex-justification: vulnerable_code_not_in_execute_path
  - vulnerability: CVE-2026-45447
    vex-justification: vulnerable_code_not_in_execute_path

  # Ignore all npm vulnerabilities. This project relies on `npm audit` instead.
  - package:
      type: npm

check-for-app-update: false
