# Configuration file for Grype (https://github.com/anchore/grype)

output: json
file: vulns.json

fail-on-severity: low

ignore:
  - vulnerability: CVE-2025-60876
    vex-justification: vulnerable_code_not_in_execute_path

  # Ignore all npm vulnerabilities. This project relies on `npm audit` instead.
  - package:
      type: npm

check-for-app-update: false
