# Check out Grype at: https://github.com/anchore/grype

output: json
file: vulns.json

fail-on-severity: low

ignore:
  # Ignore because this project isn't affected (no AES encryption is used).
  - vulnerability: CVE-2023-1255

  # Ignore all npm vulnerabilities. This project relies on `npm audit` instead.
  - package:
      type: npm
