# Check out Licensed at: https://github.com/github/licensed

root: true

sources:
  npm: true

allowed:
  - 0bsd
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - gpl-2.0-only
  - gpl-2.0-or-later
  - isc
  - mit
  - openssl
  - python-2.0
  - zlib

reviewed:
  npm:
    - "@typescript-eslint/parser@5.45.1" # bsd-2-clause
    - "@typescript-eslint/typescript-estree@5.45.1" # bsd-2-clause
    - argparse@2.0.1 # python-2.0
    - color-convert@2.0.1 # mit
    - doctrine@3.0.0 # apache-2.0
    - esquery@1.4.0 # bsd-3-clause
    - esrecurse@4.3.0 # bsd-2-clause
    - estraverse@5.3.0 # bsd-2-clause
    - esutils@2.0.3 # bsd-2-clause
    - fs.realpath@1.0.0 # isc
    - glob@7.2.3 # isc
    - ignore@5.2.0 # mit
    - lodash.merge@4.6.2 # mit
    - type-fest@0.20.2 # mit or cc0-1.0
    - uri-js@4.4.1 # bsd-2-clause

cache_path: .tmp/
