name: Audit (release)
on:
  schedule:
    - cron: 0 3 * * *
  workflow_dispatch: ~

permissions: read-all

jobs:
  audit:
    name: Audit ${{ matrix.release }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - release: v0
            main: main
    steps:
      # Setup
      - name: Checkout release
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        id: checkout
        with:
          ref: ${{ matrix.release }}
          persist-credentials: false
      - name: Install asdf
        uses: asdf-vm/actions/setup@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
      - name: Configure asdf plugins
        run: |
          asdf plugin add diffoci https://github.com/ericcornelissen/asdf-diffoci
      - name: Install tooling
        uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
      - name: Install Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: npm
          node-version-file: .nvmrc

      # Audit
      - name: Insert custom configuration
        env:
          GRYPERC: ${{ vars.GRYPERC }}
          NDMRC: ${{ vars.NDMRC }}
        run: |
          echo 'Grype configuration'
          echo "${GRYPERC}" | tee .grype.yml
          echo 'Depreman configuration'
          echo "${NDMRC}" | tee .ndmrc
      - name: Audit production dependencies
        run: |
          make audit-deprecations-npm ARGS="--omit=dev"
          make audit-vulnerabilities-image
          make audit-vulnerabilities-npm ARGS="--omit dev"
      - name: Upload SBOM and vulnerability scan
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        if: ${{ failure() }}
        with:
          if-no-files-found: error
          name: container-scan-${{ steps.checkout.outputs.commit }}
          path: |
            sbom-syft.json
            vulns.json

      # Trigger release
      - name: Checkout main
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        if: ${{ failure() }}
        with:
          ref: ${{ matrix.main }}
          persist-credentials: false
      - name: Create token to create Pull Request
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        if: ${{ failure() }}
        id: automation-token
        with:
          client-id: ${{ secrets.AUTOMATION_ID }}
          permission-actions: write # To trigger another workflow
          permission-contents: read
          private-key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
      - name: Trigger new release if main is clean
        if: ${{ failure() }}
        env:
          GH_TOKEN: ${{ steps.automation-token.outputs.token }}
        run: |
          make audit
          gh workflow run release.yml -f update_type=patch
