name: Audit
on:
  pull_request:
    paths:
      - .github/workflows/audit-dev.yml
      - .grype.yml
      - .ndmrc
      - .syft.yml
  schedule:
    - cron: 0 1 * * 2
  workflow_dispatch: ~

permissions: read-all

jobs:
  audit:
    name: Dev
    uses: $/.github/workflows/reusable-audit.yml
