name: Check
on:
  pull_request: ~
  push:
    branches:
      - main
      - v0

permissions: read-all

jobs:
  build:
    name: Build with ${{ matrix.engine }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        engine:
          - docker
          - podman
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Build
        env:
          ENGINE: ${{ matrix.engine }}
        run: make build "ENGINE=${ENGINE}"
  check:
    name: ${{ matrix.what }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        what:
          - ci
          - formatting
          - image
          - md
          - yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install asdf
        uses: asdf-vm/actions/setup@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
      - name: Configure asdf plugins
        run: |
          asdf plugin add diffoci https://github.com/ericcornelissen/asdf-diffoci
      - name: Install tooling
        uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
      - name: Check
        env:
          WHAT: ${{ matrix.what }}
        run: make "check-${WHAT}"
  codeql:
    name: CodeQL (actions)
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # To upload CodeQL results
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Initialize CodeQL
        uses: github/codeql-action/init@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
        with:
          config-file: ./.github/codeql.yml
          languages: actions
      - name: Perform CodeQL analysis
        uses: github/codeql-action/analyze@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
  licenses:
    name: Licenses
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Install asdf
        uses: asdf-vm/actions/setup@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
      - name: Configure asdf plugins
        run: |
          asdf plugin add diffoci https://github.com/ericcornelissen/asdf-diffoci
      - name: Install tooling
        uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
      - name: Check container image licenses
        if: ${{ failure() || success() }}
        run: make check-licenses-image
      - name: Check npm licenses
        if: ${{ failure() || success() }}
        run: make check-licenses-npm
  semgrep:
    name: Semgrep
    runs-on: ubuntu-24.04
    permissions:
      security-events: write # To upload SARIF results
    container:
      image: semgrep/semgrep:1.157.0
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Perform Semgrep analysis
        run: semgrep --sarif --output semgrep.sarif
      - name: Upload Semgrep report to GitHub
        uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
        if: ${{ failure() || success() }}
        with:
          sarif_file: semgrep.sarif
  reproducible-build:
    name: Reproducible build
    runs-on: ubuntu-24.04
    needs:
      - build
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Install asdf
        uses: asdf-vm/actions/setup@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
      - name: Configure asdf plugins
        run: |
          asdf plugin add diffoci https://github.com/ericcornelissen/asdf-diffoci
      - name: Install tooling
        uses: asdf-vm/actions/install@b7bcd026f18772e44fe1026d729e1611cc435d47 # v4.0.1
      - name: Check reproducibility
        run: make reproducible-build
  test:
    name: Test with ${{ matrix.engine }}
    runs-on: ubuntu-24.04
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        engine:
          - docker
          - podman
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Test
        env:
          ENGINE: ${{ matrix.engine }}
        run: make test "ENGINE=${ENGINE}"
