name: Labeler
on:
  pull_request_target: ~

permissions: read-all

jobs:
  label:
    name: Label
    permissions:
      pull-requests: write # To assign labels
    runs-on: ubuntu-22.04
    steps:
      - name: Harden runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845 # v2.4.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
      - name: Set labels on Pull Request
        uses: actions/labeler@0967ca812e7fdc8f5f71402a1b486d5bd061fe20 # v4.2.0
        with:
          configuration-path: .github/labeler.yml
          sync-labels: ""
