name: Labeler
on:
  pull_request_target: ~

permissions: read-all

jobs:
  label:
    name: Label
    permissions:
      pull-requests: write # To assign labels
    runs-on: ubuntu-24.04
    steps:
      - name: Set labels on Pull Request
        uses: actions/labeler@634933edcd8ababfe52f92936142cc22ac488b1b # v6.0.1
        with:
          configuration-path: .github/labeler.yml
          sync-labels: false
