name: Labeler
on:
  pull_request_target: ~

permissions: read-all

jobs:
  label:
    name: Label
    permissions:
      pull-requests: write # To assign labels
    runs-on: ubuntu-24.04
    steps:
      - name: Set labels on Pull Request
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          configuration-path: .github/labeler.yml
          sync-labels: false
