name: Nightly
on:
  schedule:
    - cron: 0 3 * * *
  workflow_dispatch: ~

permissions: read-all

jobs:
  audit:
    name: Audit
    uses: ericcornelissen/js-regex-security-scanner/.github/workflows/reusable-audit.yml@main
    with:
      refs: |-
        ["main", "v0"]
  tooling:
    name: Tool update ${{ matrix.tool }}
    runs-on: ubuntu-22.04
    permissions:
      contents: write # To push a commit
      pull-requests: write # To open a Pull Request
    strategy:
      fail-fast: false
      matrix:
        tool:
          - actionlint
          - cosign
          - grype
          - hadolint
          - shellcheck
          - syft
          - yamllint
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1f99358870fe1c846a3ccba386cc2b2246836776 # v2.2.1
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            files.pythonhosted.org:443
            fulcio.sigstore.dev:443
            github.com:443
            gitlab.com:443
            objects.githubusercontent.com:443
            pypi.org:443
            rekor.sigstore.dev:443
            sigstore-tuf-root.storage.googleapis.com:443
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Install tooling
        uses: asdf-vm/actions/install@2368b9def7a1194d67ae0afd9cbbd01e15f658a0 # v2.0.0
      - name: Create token to create Pull Request
        uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92 # v1.8.0
        id: release-token
        with:
          app_id: ${{ secrets.RELEASE_APP_ID }}
          private_key: ${{ secrets.RELEASE_APP_PRIVATE_KEY }}
      - name: Get latest version
        id: version
        run: |
          LATEST_VERSION="$(asdf latest '${{ matrix.tool }}')"
          echo "latest=$LATEST_VERSION" >> "$GITHUB_OUTPUT"
      - name: Install new version
        run: |
          asdf install '${{ matrix.tool }}' '${{ steps.version.outputs.latest }}'
      - name: Apply latest version to .tool-versions
        run: |
          asdf local '${{ matrix.tool }}' '${{ steps.version.outputs.latest }}'
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@d7db273d6c7206ba99224e659c982ae34a1025e3 # v4.2.1
        with:
          token: ${{ steps.release-token.outputs.token }}
          title: Update ${{ matrix.tool }} to v${{ steps.version.outputs.latest }}
          body: |
            _This Pull Request was created automatically_

            ---

            Bump ${{ matrix.tool }} to v${{ steps.version.outputs.latest }}
          branch: tooling-${{ matrix.tool }}-${{ steps.version.outputs.latest }}
          labels: dependencies
          commit-message: Update ${{ matrix.tool }} to ${{ steps.version.outputs.latest }}
          add-paths: |
            .tool-versions
