name: Nightly
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions: read-all

jobs:
  audit:
    name: Audit
    uses: ericcornelissen/js-regex-security-scanner/.github/workflows/reusable-audit.yml@main
    permissions:
      contents: write
    with:
      refs: '["main", "v0"]'
