name: Release
on:
  workflow_dispatch:
    inputs:
      update_type:
        description: Update type
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions: read-all

jobs:
  initiate:
    name: Initiate
    runs-on: ubuntu-24.04
    permissions:
      contents: write # To push a commit
      pull-requests: write # To open a Pull Request
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Create token to create Pull Request
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: automation-token
        with:
          client-id: ${{ secrets.AUTOMATION_ID }}
          private-key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
      - name: Bump version
        env:
          UPDATE_TYPE: ${{ github.event.inputs.update_type }}
        run: node scripts/bump-version.js "${UPDATE_TYPE}"
      - name: Update the changelog
        run: node scripts/bump-changelog.js
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ steps.automation-token.outputs.token }}
          REPOSITORY: ${{ github.repository }}
          UPDATE_TYPE: ${{ github.event.inputs.update_type }}
        run: |
          git remote set-url 'origin' "https://x-access-token:${GH_TOKEN}@github.com/${REPOSITORY}"

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

          git checkout -B "release-${UPDATE_TYPE}"
          git add 'CHANGELOG.md' 'Containerfile'
          git commit --message 'Version bump'
          git push --force 'origin' "release-${UPDATE_TYPE}"

          gh pr create \
            --base='main' --head="release-${UPDATE_TYPE}" \
            --title="New ${UPDATE_TYPE} release for v0" \
            --body='_This Pull Request was created automatically_

          ---

          ### Merge checklist

          - [ ] All continuous integration checks passed.
          - [ ] The version number is updated in `Containerfile`.
          - [ ] The new release is added to `CHANGELOG.md` with the correct version number and date.
          - [ ] The new version number is in accordance with the [Semantic Versioning] rules.
          - [ ] There are no other changes in the Pull Request.

          ### Post-merge

          _It will take a few minutes for this to happen._

          - [ ] A git tag for the new release is created.
          - [ ] The major version branch is updated.
          - [ ] The new version is published as a [GitHub release].
          - [ ] The new version is published to [Docker].
          - [ ] The new version is published to [GHCR].

          [docker]: https://hub.docker.com/r/ericornelissen/js-re-scan
          [ghcr]: https://github.com/ericcornelissen/js-regex-security-scanner/pkgs/container/js-re-scan
          [github release]: https://github.com/ericcornelissen/js-regex-security-scanner/releases
          [semantic versioning]: https://semver.org/spec/v2.0.0.html'
