name: Audit
on:
  workflow_call:
    inputs:
      refs:
        default: '[""]'
        required: false
        type: string

permissions: read-all

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ref: ${{ fromJSON(inputs.refs) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          ref: ${{ matrix.ref }}
      - name: Download Syft and Grype
        run: make .bin/syft .bin/grype
      - name: Create SBOM
        run: make sbom
      - name: Scan SBOM
        run: make audit-docker
      - name: Upload SBOM and vulnerability scan
        uses: actions/upload-artifact@83fd05a356d7e2593de66fc9913b3002723633cb
        if: ${{ always() }}
        with:
          if-no-files-found: error
          name: container-scan-${{ matrix.ref }}
          path: |
            sbom.json
            vulns.json
  npm:
    name: npm
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ref: ${{ fromJSON(inputs.refs) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          ref: ${{ matrix.ref }}
      - name: Install Node.js
        uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516
        with:
          node-version: 18
          cache: npm
      - name: Install Node.js dependencies
        run: npm ci
      - name: Audit all npm dependencies
        if: ${{ !startsWith(matrix.ref, 'v') }}
        run: make audit-npm
      - name: Audit production npm dependencies
        if: ${{ startsWith(matrix.ref, 'v') }}
        run: make audit-npm ARGS="--omit dev"
  secrets:
    name: Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          fetch-depth: 0 # To allow for historic scans
      - name: Scan for secrets
        uses: gitleaks/gitleaks-action@5425999620c418539c61a8143f29e346d5f6cf08
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_ENABLE_COMMENTS: false
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: false
          GITLEAKS_ENABLE_SUMMARY: true
