name: Audit
on:
  workflow_call:
    inputs:
      refs:
        default: |-
          [""]
        required: false
        type: string

permissions: read-all

jobs:
  deprecations:
    name: Deprecations
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ref: ${{ fromJSON(inputs.refs) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
          ref: ${{ matrix.ref }}
      - name: Install Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Audit deprecation warnings
        run: make audit-deprecations
  image:
    name: Image
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ref: ${{ fromJSON(inputs.refs) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        id: checkout
        with:
          persist-credentials: false
          ref: ${{ matrix.ref }}
      - name: Install tooling
        uses: asdf-vm/actions/install@4f8f7939dd917fc656bb7c3575969a5988c28364 # v3.0.0
      - name: Audit dependencies in container image
        run: make audit-image
      - name: Upload SBOM and vulnerability scan
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874 # v4.4.0
        if: ${{ failure() || success() }}
        with:
          if-no-files-found: error
          name: container-scan-${{ steps.checkout.outputs.commit }}
          path: |
            sbom-syft.json
            vulns.json
  npm:
    name: npm
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ref: ${{ fromJSON(inputs.refs) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
          ref: ${{ matrix.ref }}
      - name: Install Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Audit all npm dependencies
        if: ${{ !startsWith(matrix.ref, 'v') }}
        run: make audit-npm
      - name: Audit production npm dependencies
        if: ${{ startsWith(matrix.ref, 'v') }}
        run: make audit-npm ARGS="--omit dev"
