name: Audit
on:
  workflow_call:
    inputs:
      ref:
        required: false
        type: string
    secrets:
      SNYK_TOKEN:
        required: true

permissions: read-all

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    env:
      SBOM_FILE: sbom.json
      VULN_FILE: vulns.json
    steps:
      - name: Checkout Code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: ${{ inputs.ref }}
      - name: Download Syft and Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b ./bin v0.57.0
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh  | sh -s -- -b ./bin v0.50.2
      - name: Build
        run: docker build --tag ericornelissen/js-re-scan .
      - name: Create SBOM
        run: |
          ./bin/syft ericornelissen/js-re-scan:latest
      - name: Scan SBOM
        run: |
          ./bin/grype ${{ env.SBOM_FILE }} -o json > ${{ env.VULN_FILE }}
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          if-no-files-found: error
          name: container-scan
          path: |
            ${{ env.SBOM_FILE }}
            ${{ env.VULN_FILE }}
  npm:
    name: npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          ref: ${{ inputs.ref }}
      - name: Install Node.js
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: 18
          cache: npm
      - name: Install Node.js dependencies
        run: npm ci
      - name: Audit npm dependencies
        run: npm audit
