name: Audit
on:
  workflow_call:
    inputs:
      refs:
        default: |-
          [""]
        required: false
        type: string

permissions: read-all

jobs:
  deprecations:
    name: Deprecations
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ref: ${{ fromJSON(inputs.refs) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
          ref: ${{ matrix.ref }}
      - name: Install Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Insert custom configuration
        if: ${{ startsWith(matrix.ref, 'v') }}
        env:
          NDMRC: ${{ vars.NDMRC }}
        run: echo "${NDMRC}" | tee .ndmrc
      - name: Audit all deprecation warnings
        if: ${{ !startsWith(matrix.ref, 'v') }}
        run: make audit-deprecations-npm
      - name: Audit production deprecation warnings
        if: ${{ startsWith(matrix.ref, 'v') }}
        run: make audit-deprecations-npm ARGS="--omit dev"
  image:
    name: Image
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ref: ${{ fromJSON(inputs.refs) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        id: checkout
        with:
          persist-credentials: false
          ref: ${{ matrix.ref }}
      - name: Install tooling
        uses: asdf-vm/actions/install@4f8f7939dd917fc656bb7c3575969a5988c28364 # v3.0.0
      - name: Insert custom configuration
        if: ${{ startsWith(matrix.ref, 'v') }}
        env:
          GRYPERC: ${{ vars.GRYPERC }}
        run: echo "${GRYPERC}" | tee .grype.yml
      - name: Audit dependencies in container image
        run: make audit-vulnerabilities-image
      - name: Upload SBOM and vulnerability scan
        uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4.5.0
        if: ${{ failure() || success() }}
        with:
          if-no-files-found: error
          name: container-scan-${{ steps.checkout.outputs.commit }}
          path: |
            sbom-syft.json
            vulns.json
  npm:
    name: npm
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        ref: ${{ fromJSON(inputs.refs) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
          ref: ${{ matrix.ref }}
      - name: Install Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          cache: npm
          node-version-file: .nvmrc
      - name: Audit all npm dependencies
        if: ${{ !startsWith(matrix.ref, 'v') }}
        run: make audit-vulnerabilities-npm
      - name: Audit production npm dependencies
        if: ${{ startsWith(matrix.ref, 'v') }}
        run: make audit-vulnerabilities-npm ARGS="--omit dev"
