name: Semgrep
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-22.04
    permissions:
      security-events: write # To upload SARIF results
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - name: Perform Semgrep analysis
        run: semgrep ci --sarif --output semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      - name: Upload Semgrep report to GitHub
        uses: github/codeql-action/upload-sarif@8f596b4ae3cb3c588a5c46780b86dd53fef16c52 # v3.25.2
        if: ${{ failure() || success() }}
        with:
          sarif_file: semgrep.sarif
