name: Semgrep
on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-22.04
    permissions:
      security-events: write # To upload SARIF results
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Perform Semgrep analysis
        run: semgrep ci --sarif --output semgrep.sarif
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
      - name: Upload Semgrep report to GitHub
        uses: github/codeql-action/upload-sarif@04daf014b50eaf774287bf3f0f1869d4b4c4b913 # v2.21.7
        if: ${{ failure() || success() }}
        with:
          sarif_file: semgrep.sarif
