name: Check
on:
  - push
  - pull_request

permissions: read-all

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.0.2
      - name: Build
        run: docker build --tag ericornelissen/js-re-scan .
  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.0.2
        with:
          submodules: true
      - name: Install Node.js
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18
          cache: npm
      - name: Install Node.js dependencies
        run: npm ci
      - name: Build
        run: docker build --tag ericornelissen/js-re-scan .
      - name: Test
        run: npm run ava
