name: Check
on:
  pull_request:
  push:
    branches:
      - main
      - v0

permissions: read-all

jobs:
  audit:
    name: Audit
    uses: ericcornelissen/js-regex-security-scanner/.github/workflows/reusable-audit.yml@main
    needs:
      - build
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Build
        run: make build
  licenses:
    name: Licenses
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Install Node.js
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: 18
          cache: npm
      - name: Install Licensed
        uses: jonabc/setup-licensed@d477a8f55b137ce955453cfd42cb0b438ba2e3e6
        with:
          install-dir: ./.bin/
          version: 3.7.3
      - name: Install Node.js dependencies
        run: npm ci
      - name: Catalogue licenses
        run: ./.bin/licensed cache
      - name: Create NOTICE
        run: ./.bin/licensed notices
      - name: Upload NOTICE
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8
        with:
          if-no-files-found: error
          name: notices-${{ github.sha }}
          path: |
            .tmp/licensed/NOTICE
      - name: Check licenses
        run: ./.bin/licensed status
  test:
    name: Test
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout Code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          submodules: true
      - name: Install Node.js
        uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93
        with:
          node-version: 18
          cache: npm
      - name: Install Node.js dependencies
        run: npm ci
      - name: Test
        run: make test
