name: Tooling
on:
  schedule:
    - cron: 0 3 * * *
  workflow_dispatch: ~

permissions: read-all

jobs:
  reproducible-builds:
    name: Reproduce latest release
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
          ref: v0
      - name: Build latest image
        run: TAG=rebuid ENGINE_OPTIONS=--no-cache make build
      - name: Pull published image
        run: docker.io/ericornelissen/js-re-scan:latest
      - name: Diff images
        run: |
          diffoci diff --semantic \
            docker://docker.io/ericornelissen/js-re-scan:latest \
            docker://docker.io/ericornelissen/js-re-scan:rebuild
  update:
    name: Update Tooling
    runs-on: ubuntu-24.04
    permissions:
      contents: write # To push a commit
      pull-requests: write # To open a Pull Request
    steps:
      - name: Create token to create Pull Request
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        id: automation-token
        with:
          app-id: ${{ secrets.AUTOMATION_ID }}
          private-key: ${{ secrets.AUTOMATION_PRIVATE_KEY }}
      - name: Update tooling
        uses: ericcornelissen/tool-versions-update-action/pr@aa1815a7caf1aecd37208e34ad57bec973bcd507 # v2.2.1
        with:
          commit-message: Bump {{updated-tools}} from {{updated-old-versions}} to {{updated-new-versions}}
          labels: dependencies
          max: 1
          pr-body: |
            Bumps {{updated-tools}} from {{updated-old-versions}} to {{updated-new-versions}}.

            ---

            _This Pull Request was created using the [tool-versions-update-action]_

            [tool-versions-update-action]: https://github.com/ericcornelissen/tool-versions-update-action
          pr-title: Bump {{updated-tools}} from {{updated-old-versions}} to {{updated-new-versions}}
          plugins: |
            diffoci https://github.com/ericcornelissen/asdf-diffoci
          token: ${{ steps.automation-token.outputs.token }}
